### ISSUE TITLE
Unexpected truncate if text contains null char `\x00`

### ISSUE THREAD

**Issue by scruel** [manticoresoftware/manticoresearch-python#18]
```python
import manticoresearch
table_name = 'test'
manticoresearch_config = manticoresearch.Configuration(
    host="http://127.0.0.1:9308")
manticoresearch_client = manticoresearch.ApiClient(manticoresearch_config)
utilsApi = manticoresearch.UtilsApi(manticoresearch_client)
indexApi = manticoresearch.IndexApi(manticoresearch_client)
utilsApi.sql(
    f"CREATE TABLE IF NOT EXISTS {table_name}(id bigint fast_fetch='0', title text fast_fetch='0')"
    "morphology='stem_en' engine='columnar'"
)

doc = {"index": table_name, "id": 1,
       "doc": {"title": 'a\x00sdfg'}}
indexApi.insert(doc)
res = utilsApi.sql(f"select * from {table_name}")
print(res[0]['data'][0]['title'])
```
Result:
```
a
```

IMO it caused by C++ treats `/x00` as the end of the string?

**Comment by klirichek** [comment]
mre:
```
curl -sX POST http://localhost:9312/insert  -d '{"index":"test","id":1,"doc":{"title":"a\u0000sdfg"}}'
```
(python internally subsitutes \x00 into \u0000 and send resulting line to manticore).

Manticure uses lib 'cjson' to parse incoming json. That is written in C and operates with asciiz strings.
After decoding "a\u0000sdfg" it has zero after first 'a', and so, that is returned as final result.
Need to discuss, if we want to deal with it, or just won't fix, because any fix here implies either patch develop and patch 3-rd party lib (cjson), either research and use another lib for json parsing. And it looks dangerous for other libraries (like stemmer, icu, etc.) which might expect asciiz and will process such string-with-zero-inside same way (i.e. truncating it by zero). So, there is enormous spread of edge cases looking as a large issue

**Comment by sanikolaev** [comment]
@scruel 

When you do
```
doc = {"index": table_name, "id": 1,
       "doc": {"title": 'a\x00sdfg'}}
```

What do you mean? Do you want the string to be stored in Manticore including the null byte or you mean that the string should be stored exactly as `a\x00sdfg` (without the null-byte, but with these 4 bytes instead: `\x00`)?

**Comment by scruel** [comment]
@sanikolaev including the null byte, we currently have to remove all `\x00` byte from the text.

**Comment by sanikolaev** [comment]
I've [added to the documentation](https://manual.manticoresearch.com/dev/Creating_a_table/Data_types#Storing-binary-data-in-Manticore) that Manticore string/text fields are not meant for storing binary data. If you need to store binary data, you can base64-encode it (by the way, Elasticsearch requires the same approach as mentioned [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/binary.html)).

I'll close this issue. Feel free to reopen in case some new details arise.
